#!/usr/bin/env python3
"""Generate C/JS registry tables from the authoritative wire-schema.json."""
import json
import sys
from pathlib import Path
root=Path(__file__).resolve().parents[2]
schema=json.loads((root/'librrprotocol/wire-schema.json').read_text())
reserved = {'msg', 'cmd', 'object', 'property'}
for group in schema['groups']:
 for field in group['fields'].values():
  if reserved.intersection(field.split('.')): raise SystemExit('Reserved wire field: ' + field)
rows=['/* Generated by tests/generate_wire.py; edit wire-schema.json. */']
for i,g in enumerate(schema['groups']):
 rows.append(f'static const rr_wire_field_t wire_fields_{i}[] = {{')
 rows.extend('   {'+json.dumps(k)+', '+json.dumps(v)+'},' for k,v in g['fields'].items())
 rows.append('};')
rows.append('static const rr_wire_rule_t wire_rules[] = {')
for i,g in enumerate(schema['groups']):
 for op,cmd in g['operations'].items():
  vals=[json.dumps(op),json.dumps(g['type']),json.dumps(g['command_key']) if g['command_key'] else 'NULL',json.dumps(cmd) if cmd else 'NULL',f'wire_fields_{i}',f'sizeof(wire_fields_{i}) / sizeof(wire_fields_{i}[0])']
  rows.append('   {'+', '.join(vals)+'},')
rows.append('};')
outputs={'librrprotocol/wire-version.h':'/* Generated from wire-schema.json. */\n#define RR_PROTOCOL_VERSION '+str(schema['version'])+'\n#define RR_WS_SUBPROTOCOL '+json.dumps(schema['websocket_subprotocol'])+'\n', 'librrprotocol/wire-registry.h':'\n'.join(rows)+'\n', 'www/js/webui.wire.registry.js':'/* Generated from librrprotocol/wire-schema.json. */\nconst rrWireSchema = '+json.dumps(schema,separators=(',',':'))+';\nif (typeof module !== "undefined") module.exports = rrWireSchema;\n'}
for name,text in outputs.items():
 path=root/name
 if '--check' in sys.argv:
  if not path.exists() or path.read_text()!=text:raise SystemExit('Out of date: '+name)
 else:path.write_text(text)
